<?xml version="1.0" encoding="ISO-8859-1"?>
<!--Question Specification Document for the ClassAction Project-->
<!DOCTYPE QuestionBank [
    <!ELEMENT QuestionBank (Question+)>
    <!ELEMENT Question (Name, Description, Keywords, Type, File, Width, Height, RelevantImages, RelevantAnimations, RelevantOutlines, RelevantTables)>
    <!ATTLIST Question
          id CDATA #REQUIRED>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT Keywords (Keyword*)>
	<!ELEMENT Keyword (#PCDATA)>
	<!ELEMENT Type (#PCDATA)>
	<!ELEMENT File (#PCDATA)>
	<!ELEMENT Width (#PCDATA)>
	<!ELEMENT Height (#PCDATA)>
	<!ELEMENT RelevantImages (RelevantImage*)>
	<!ELEMENT RelevantImage (#PCDATA)>
	<!ELEMENT RelevantAnimations (RelevantAnimation*)>
	<!ELEMENT RelevantAnimation (#PCDATA)>
	<!ELEMENT RelevantOutlines (RelevantOutline*)>
	<!ELEMENT RelevantOutline (#PCDATA)>
	<!ELEMENT RelevantTables (RelevantTable*)>
	<!ELEMENT RelevantTable (#PCDATA)>
]>
<QuestionBank>
  <Question id="ca_divider_0">
    <Name>------------------------------------------------------------</Name>
    <Description/>
    <Keywords/>
    <Type>0</Type>
    <File/>
    <Width/>
    <Height/>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_divider_1">
    <Name>------------------------------------------------------------</Name>
    <Description/>
    <Keywords/>
    <Type>1</Type>
    <File/>
    <Width/>
    <Height/>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_divider_2">
    <Name>------------------------------------------------------------</Name>
    <Description/>
    <Keywords/>
    <Type>2</Type>
    <File/>
    <Width/>
    <Height/>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_divider_3">
    <Name>------------------------------------------------------------</Name>
    <Description/>
    <Keywords/>
    <Type>3</Type>
    <File/>
    <Width/>
    <Height/>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <!-- Introductory Concepts Module -->
  <Question id="ca_intro_scale">
    <Name>Scale</Name>
    <Description>This question uses a diagram to test the student's knowledge of categorization for various astronomical objects (Jupiter, Virgo Supercluster, Polaris, Andromeda Galaxy, Comet Halley, and the Orion Nebula).  The student is given the name of the object and is asked to place it in one of three hierarchical categories: Solar System, Milky Way, or Universe.</Description>
    <Keywords>
      <Keyword>category</Keyword>
      <Keyword>Jupiter</Keyword>
      <Keyword>Virgo Supercluster</Keyword>
      <Keyword>Polaris</Keyword>
      <Keyword>Andromeda Galaxy</Keyword>
      <Keyword>Comet Halley</Keyword>
      <Keyword>Orion Nebula</Keyword>
      <Keyword>hierarchy</Keyword>
      <Keyword>solar system</Keyword>
      <Keyword>milky way</Keyword>
      <Keyword>universe</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_scale.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_increasingdist">
    <Name>Increasing Distance</Name>
    <Description>This question asks the students to place a list of astronomical objects (various planets, stars, galaxies, and superclusters) in order of increasing distance from Earth.</Description>
    <Keywords>
      <Keyword>distance</Keyword>
      <Keyword>planet</Keyword>
      <Keyword>star</Keyword>
      <Keyword>galaxy</Keyword>
      <Keyword>supercluster</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_increasingdist.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_scientnot">
    <Name>Scientific Notation</Name>
    <Description>This question asks the student to convert units of measure to and from scientific notation, as well as to converts metric prefixes to their corresponding numbers in scientific notation.</Description>
    <Keywords>
      <Keyword>scientific notation</Keyword>
      <Keyword>metric prefixes</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_scientnot.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
 <Question id="ca_intro_calcscientnot">
    <Name>Calculation in Scientific Notation</Name>
    <Description>This question asks students to calculate various distances to various objects based on various units of measure (solar radii, astronomical units, galactic radii), as well as to use the number of stars in the galaxy as a basis to estimate the number of stars in the universe, in order that the student becomes familiar with basic mathematics using scientific notation.</Description>
    <Keywords>
      <Keyword>scientific notation</Keyword>
      <Keyword>calculate</Keyword>
      <Keyword>math</Keyword>
      <Keyword>solar radii</Keyword>
      <Keyword>astronomical units</Keyword>
      <Keyword>galactic radii</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_calcscientnot.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
   <Question id="ca_intro_specialunits">
    <Name>Special Units</Name>
    <Description>This question asks the student to determine the most logical unit of measure for various distances (to the nearest state, planet, star, etc.), using light years, parsecs, astronomical units, meters, and all metric prefix permutations of these.</Description>
    <Keywords>
      <Keyword>unit</Keyword>
      <Keyword>distance</Keyword>
      <Keyword>light year</Keyword>
      <Keyword>parsec</Keyword>
      <Keyword>astronomical unit</Keyword>
      <Keyword>meter</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_specialunits.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_dimanalysis">
    <Name>Dimensional Analysis</Name>
    <Description>This questions asks the students to extrapolate various dimensions of astronomical bodies based on their radii, volumes, etc (determine the radius of Jupiter based on how many Earths fit inside, the cross-section of a particle in Saturn's ring given the radius, and the surface area of such a particle given the radius).</Description>
    <Keywords>
      <Keyword>dimension</Keyword>
      <Keyword>radius</Keyword>
      <Keyword>volume</Keyword>
      <Keyword>cross-section</Keyword>
      <Keyword>surface area</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_dimanalysis.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_lttime">
    <Name>Light-Travel Time</Name>
    <Description>This question involves the speed of light as related to time and distance.  The student is asked either to determine a distance in light years using a hypothetical speed of light, determine a distance a photon travels during a given period of time, or determine how much time it takes for a photon to travel a certain distance.</Description>
    <Keywords>
      <Keyword>speed of light</Keyword>
      <Keyword>distance</Keyword>
      <Keyword>time</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_lttime.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_lookbacktime">
    <Name>Look-Back Time</Name>
    <Description>This question asks the student to determine how long it would take light emitted from a given object (a galaxy or a supernova) to reach an observer on Earth, also known as the look-back time for that object.  The students are also asked to give the date an event might have occurred, as well as a projected date of knowledge of the event for an observer on Earth.</Description>
    <Keywords>
      <Keyword>look-back time</Keyword>
      <Keyword>light</Keyword>
      <Keyword>time</Keyword>
      <Keyword>date</Keyword>
      <Keyword>Earth observer</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_lookbacktime.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
       <RelevantAnimation>lookbacktimesim</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_radiuscircgraphs">
    <Name>Graph: Circumference</Name>
    <Description>This question tests the student's ability to put an equation into graph-form, in this case using radius vs. circumference.</Description>
    <Keywords>
      <Keyword>graph</Keyword>
      <Keyword>radius</Keyword>
      <Keyword>circumference</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_radiuscircgraphs.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_earthrotations">
    <Name>Earth Rotations</Name>
    <Description>This question asks the student to differentiate between rotation and revolution.  The student is to determine how many rotations the Earth has gone through in a given number of revolutions around the sun.</Description>
    <Keywords>
      <Keyword>rotation</Keyword>
      <Keyword>revolution</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_earthrotations.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_highprecisionlowaccuracy">
    <Name>Precision/Accuracy</Name>
    <Description>The student is shown four groups of arrows in a target, and is asked to differentiate between the precision of the archer's shooting as and the archer's accuracy.</Description>
    <Keywords>
      <Keyword>precision</Keyword>
      <Keyword>accuracy</Keyword>
      <Keyword>arrows</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_highprecisionlowaccuracy.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_commondensities">
    <Name>Common Densities</Name>
    <Description>Students are asked to identify the largest and smallest values in a list of densities of common substances.</Description>
    <Keywords>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_commondensities.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
     <RelevantTables>
       <RelevantTable>densities</RelevantTable>
    </RelevantTables>
  </Question>
  <Question id="ca_intro_densityandvolume">
    <Name>Density and Volume</Name>
    <Description>Student understanding of the relationship between density, mass, and volume is probed.</Description>
    <Keywords>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_densityandvolume.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_trashdensity">
    <Name>Trash Density</Name>
    <Description>Students are asked to identify the appropriate graph of density vs time for the contents of a trash compactor.</Description>
    <Keywords>
    </Keywords>
    <Type>1</Type>
    <File>questions/intro/ca_intro_trashdensity.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_densitycombinedobject">
    <Name>Density of Combined Object</Name>
    <Description>Students are asked to identify what happens to the density when identical objects are combined.</Description>
    <Keywords/>
    <Type>1</Type>
    <File>questions/intro/ca_intro_densitycombinedobject.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_propertiesofdensity">
    <Name>Properties of Density</Name>
    <Description>Students are asked what happens to the density when an object with a uniform density is cut in pieces.</Description>
    <Keywords/>
    <Type>1</Type>
    <File>questions/intro/ca_intro_propertiesofdensity.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_intro_spinlookback">
    <Name>Spin Lookback Time</Name>
    <Description>Occurrences in the Sci-Fi book Spin are used to motivate a discussion of light travel time.</Description>
    <Keywords/>
    <Type>3</Type>
    <File>questions/intro/ca_intro_spinlookback.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
       <RelevantAnimation>lookbacktimesim</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <!-- Basic Motions & Ancient Astronomy  -->
  <Question id="ca_ancientastro_northpoint">
    <Name>Star on North Point</Name>
    <Description>The student is told a star is at the north point and is asked to determine where the star will be located in the sky 6 or 12 hours later.  This tests the student's knowledge of the apparent nightly motion of stars through the sky due to the Earth's rotation.</Description>
    <Keywords>
      <Keyword>north point</Keyword>
      <Keyword>apparent motion</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_northpoint.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
	<RelevantAnimation>dipperclock</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_horizontozenith">
    <Name>From Horizon to Zenith</Name>
    <Description>The student is given the positions of three stars as they begin to rise above the horizon and the current latitude of the observer's location, and is asked to determine which will eventually reach the zenith.</Description>
    <Keywords/>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_horizontozenith.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_seasonalsky">
    <Name>Seasonal Sky Analogy</Name>
    <Description>The student is shown four diagrams of students pointing toward or away from the sun, and is asked to determine which diagram accurately depicts the reason different constellations are visible during different seasons (specifically summer and winter).</Description>
   <Keywords>
      <Keyword>constellations</Keyword>
      <Keyword>seasons</Keyword>
      <Keyword>summer</Keyword>
      <Keyword>winter</Keyword>
      <Keyword>student</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_seasonalsky.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_motionofsun">
    <Name>Apparent Motion of the Sun</Name>
    <Description>Given the actual motion of the sun, the student is asked about the apparent motion of Earth. </Description>
    <Keywords>
      <Keyword>horizon</Keyword>
      <Keyword>zenith</Keyword>
      <Keyword>latitude</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_motionofsun.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
       <RelevantAnimation>zodiac</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_planetlocations">
    <Name>Location of Planets</Name>
    <Description>The student is given a bit of historical information about the Greeks' discovery of the planets, and is asked to determine which given diagram depicts where the Greeks could (and can) look in the sky to locate these 'wanderers'.</Description>
    <Keywords>
      <Keyword>planet</Keyword>
      <Keyword>Greek</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_planetlocations.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_planetpositions">
    <Name>Planet Positions</Name>
    <Description>The student is shown the positions of different planets (Jupiter and Venus) in the sky as they are rising or setting in two different locations (Boulder and Knoxville) and is asked to determine where they would be located in 6 hours due to the rotation of the Earth.</Description>
    <Keywords>
      <Keyword>planet</Keyword>
      <Keyword>rise</Keyword>
      <Keyword>set</Keyword>
      <Keyword>Earth rotation</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_planetpositions.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_aristarchus">
    <Name>Aristarchus</Name>
    <Description>Aristarchus' experiment is shown, wherein he measured the Earth-Sun distance in terms of the Earth-Moon distance, and the student is asked why he chose to use the third-quarter moon to obtain this distance, and why his resulting distance was so much smaller than the current value.</Description>
    <Keywords>
      <Keyword>Aristarchus</Keyword>
      <Keyword>Moon</Keyword>
      <Keyword>Sun</Keyword>
      <Keyword>Earth</Keyword>
      <Keyword>distance</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_aristarchus.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
    <Question id="ca_ancientastro_angulardiametermobile">
    <Name>Angular Diameter Mobile</Name>
    <Description>Students are asked to identify the largest and smallest angular diameters for various balls at various distances.</Description>
    <Keywords/>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_angulardiametermobile.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
       <RelevantAnimation>smallangledemo</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_angulardiameterballoon">
    <Name>Angular Diameter of a Balloon</Name>
    <Description>Students are asked to identify how angular diameters changes as the size and distances of objects change.</Description>
    <Keywords/>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_angulardiameterballoon.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
       <RelevantAnimation>smallangledemo</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_moonstacking">
    <Name>Moon Stacking</Name>
    <Description>Students are asked about the angular diameter of the moon and hypothetical adjacent moons.</Description>
    <Keywords/>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_moonstacking.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages>
       <RelevantImage>fistangle</RelevantImage>
       <RelevantImage>arcseconddiagram</RelevantImage>
    </RelevantImages>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_eratosthenes">
    <Name>Eratothenes</Name>
    <Description>Eratosthenes' experiment is diagrammed where the circumference of Earth was estimated in ancient Greece. Students are asked to work with the logic related to how far the sun was off of the zenith and the separation of the two locations.</Description>
    <Keywords>
      <Keyword>Eratosthenes</Keyword>
      <Keyword>Earth Circumference</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_eratosthenes.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_eratosthenesanalogies">
    <Name>Eratosthenes Analogies</Name>
    <Description>Real world situations are presented which use the same mathematical logic as Eratosthenes' Experiment.</Description>
    <Keywords>
      <Keyword>Eratosthenes</Keyword>
      <Keyword>Earth Circumference</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_eratosthenesanalogies.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_keymound">
    <Name>Key Mound</Name>
    <Description>Key mounds (azimuth markers) are used to probem student understanding of the azimuth values of the rising and setting sun on the solstices.</Description>
    <Keywords>
      <Keyword>Key Mound</Keyword>
      <Keyword>Celestial Markers</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/ancientastro/ca_ancientastro_keymound.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_heliacalrising">
    <Name>Heliacal Rising</Name>
    <Description>The student is given the definition of the heliacal rising (based on an ancient Egyptian calendar) and is asked to determine when the reappearance of Sirius would occur in relation to the sun's rising or setting.n</Description>
    <Keywords>
      <Keyword>heliacal</Keyword>
      <Keyword>Sirius</Keyword>
      <Keyword>rise</Keyword>
      <Keyword>set</Keyword>
      <Keyword>Egypt</Keyword>
    </Keywords>
    <Type>2</Type>
    <File>questions/ancientastro/ca_ancientastro_heliacalrising.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
       <RelevantAnimation>heliacalrisingsim</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_ancientastro_morningeveningstar">
    <Name>Morning/Evening Star</Name>
    <Description>Students are asked to identify the morning stars and evening stars from top-down views of our solar system.</Description>
    <Keywords>
      <Keyword>Morning Star</Keyword>
      <Keyword>Evening Star</Keyword>
    </Keywords>
    <Type>2</Type>
    <File>questions/ancientastro/ca_ancientastro_morningeveningstar.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <!-- Coordinates and Motions
        Warm-up Questions  -->
  <Question id="ca_coordsmotion_daylightbadgood">
    <Name>Daylight</Name>
    <Description>The student is shown an animation involving a 2-dimension view of the globe, where dark and light areas represent daylight and night respectively, and is asked to determine whether or not the motions showing the changes between daylight and night on various parts of the globe is realistic or not based on the Earth's tilted rotation.</Description>
    <Keywords>
      <Keyword>daylight</Keyword>
      <Keyword>night</Keyword>
      <Keyword>rotation</Keyword>
      <Keyword>tilt</Keyword>
    </Keywords>
    <Type>0</Type>
    <File>questions/coordsmotion/ca_coordsmotion_daylightbadgood.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
      <RelevantAnimation>daylightsimulator</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_coordsmotion_diurnalwarmup">
    <Name>Diurnal Warmup</Name>
    <Description>The student is shown an animation of a star moving through the sky on a supposedly diurnal path at a certain location, and the student is asked to determine if the animation is realistic.</Description>
    <Keywords>
      <Keyword>diurnal</Keyword>
    </Keywords>
    <Type>0</Type>
    <File>questions/coordsmotion/ca_coordsmotion_diurnalwarmup.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
   <RelevantAnimations>
      <RelevantAnimation>celhorcomp</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_coordsmotion_incorrectsunanimation">
    <Name>Incorrect Sun Animation</Name>
    <Description>The student is shown an animation of a supposed animation of the sun's motion and asked "what is wrong with this animation?".  We have shown the yearly motion along the ecliptic instead of a daily motion at constant declination.</Description>
    <Keywords/>
    <Type>0</Type>
    <File>questions/coordsmotion/ca_coordsmotion_incorrectsunanimation.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
      <RelevantAnimation>sunmotions</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <!-- Coordinates and Motions: General Questions  -->
   <Question id="ca_coordsmotion_bestday">
    <Name>Best Day</Name>
    <Description>The student is asked to determine what months (and thus seasons) would be best for different activities (sledding or going to the beach) at different locations around the world (Germany, Chile, Canada, and New Zealand), representing both the northern and southern hemispheres.</Description>
    <Keywords>
      <Keyword>seasons</Keyword>
      <Keyword>northern hemisphere</Keyword>
      <Keyword>southern hemisphere</Keyword>
      <Keyword>sledding</Keyword>
      <Keyword>beach</Keyword>
      <Keyword>Germany</Keyword>
      <Keyword>Chile</Keyword>
      <Keyword>Canada</Keyword>
      <Keyword>New Zealand</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/coordsmotion/ca_coordsmotion_bestday.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
   <RelevantAnimations>
      <RelevantAnimation>sunmotions</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_coordsmotion_earthchanges">
    <Name>Change to Earth Seasons</Name>
    <Description>The student is given both the eccentricity of Earth's orbit and its obliquity (tilt), and is asked to determine how the seasons would change with various changes in those two values.</Description>
    <Keywords>
      <Keyword>season</Keyword>
      <Keyword>eccentricity</Keyword>
      <Keyword>obliquity</Keyword>
      <Keyword>tilt</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/coordsmotion/ca_coordsmotion_earthchanges.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations/>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_coordsmotion_seasonscontrib">
    <Name>Seasons Contributor(s)</Name>
    <Description>The student is asked to determine what contributes to the seasons on Earth (altitude of sun's rays, sun's time spent above horizon, proximity of Earth in relation to the sun, or a combination of the above).</Description>
    <Keywords>
      <Keyword>season</Keyword>
      <Keyword>contribute</Keyword>
      <Keyword>altitude of sun</Keyword>
      <Keyword>proximity</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/coordsmotion/ca_coordsmotion_seasonscontrib.swf</File>
    <Width>780</Width>
    <Height>515</Height>
    <RelevantImages/>
    <RelevantAnimations>
      <RelevantAnimation>sunmotions</RelevantAnimation>
      <RelevantAnimation>eclipticsimulator</RelevantAnimation>
    </RelevantAnimations>
    <RelevantOutlines/>
    <RelevantTables/>
  </Question>
  <Question id="ca_coordsmotion_noOrbitalTilt">
    <Name>No Orbital Tilt</Name>
    <Description>Asks the student to identify the manifestations of Earth having no orbital tilt. </Description>
    <Keywords>
      <Keyword>obliquity</Keyword>
      <Keyword>tilt</Keyword>
    </Keywords>
    <Type>1</Type>
    <File>questions/coordsmotion/ca_coordsmotion_noOrbitalTilt.swf</File>
    <Width>780</Width>